# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16c81ce40ca2890f22059aea7a5b00e50db0c70e4bf364ba915336bedc72712e484536e49ce956008b9f9ac493727659be82ef0ca2fa0a9b458df620c1d493e

test:
  secret_key_base: 21caa579287ff3473d2385d0bc7d6517aadf83b25b36efb09128cf429e4351a0cc51a4480d71774a505d677527ae8d4ef800930d386172882725ebb81fcd7e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
